package com.company.hibernateorm.model;

// Jakarta Persistence annotations
import jakarta.persistence.*;

/*
 * @Entity
 *
 * Marks this class as a Hibernate Entity.
 *
 * Entity means:
 * This class will become a database table.
 */

@Entity


/*
 * @Table
 *
 * Specifies table name in database.
 */

@Table(name = "StudentTable")

public class Student {

    /*
     * @Id
     *
     * Marks this field as Primary Key.
     */

    @Id


    /*
     * @GeneratedValue
     *
     * Auto-generates primary key values.
     *
     * GenerationType.IDENTITY:
     * Database handles auto increment.
     */

    @GeneratedValue(strategy = GenerationType.IDENTITY)

    private int id;
    private String name;
    private String email;
    private String course;


    /*
     * Default Constructor
     *
     * Hibernate REQUIREMENT:
     * Every entity class must have default constructor.
     */

    public Student() {

    }


    /*
     * Parameterized Constructor
     * Used while creating object with all fields.
     */

    public Student(int id, String name,
                   String email, String course) {

        super();

        this.id = id;
        this.name = name;
        this.email = email;
        this.course = course;
    }


    /*
     * Constructor without ID
     *
     * ID is auto-generated by database.
     */

    public Student(String name,
                   String email,
                   String course) {

        super();

        this.name = name;
        this.email = email;
        this.course = course;
    }


    /*
     * Getter and Setter Methods
     */

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }


    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }


    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }


    public String getCourse() {
        return course;
    }

    public void setCourse(String course) {
        this.course = course;
    }


    /*
     * toString()
     *
     * Used to print object data.
     */

    @Override
    public String toString() {

        return "Student [id=" + id +
                ", name=" + name +
                ", email=" + email +
                ", course=" + course + "]";
    }
}